version: '3.8'

services:
  expense-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    # For development, you can use volumes to enable hot reloading
    # volumes:
    #   - ./src:/app/src
    #   - ./public:/app/public