version: '3.8'

services:
  # Frontend service - for development, we'll use Vite's dev server
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./:/app
      - /app/node_modules
      # Don't mount node_modules as a volume to ensure we use the container's node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000/api
    command: npm run dev

  # Frontend service - production build
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:5000/api
    
  # Backend service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/expense_tracker
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRES_IN=1d
      - CLIENT_URL=http://localhost:3000
      - EMAIL_HOST=smtp.mailtrap.io
      - EMAIL_PORT=2525
      - EMAIL_USER=your_mailtrap_user
      - EMAIL_PASS=your_mailtrap_password
      - EMAIL_FROM=noreply@bitbudget.com
    volumes:
      - ./server:/app
      - /app/node_modules
      
  # Database service
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=expense_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: